import mongoose from "mongoose";
import { withCommonFields } from "./_baseSchema.js";
import { STATES } from "../config/constants.js";

const CLASS_SOUGHT = [
  "LKG", "UKG", "Class 1", "Class 2", "Class 3", "Class 4", "Class 5",
  "Class 6", "Class 7", "Class 8", "Class 9", "Class 10", "Class 11", "Class 12",
];

const admissionSchema = new mongoose.Schema({
  academic_year: { type: String, required: true },
  unique_id: { type: String },
  application_no: { type: String, required: true, unique: true },
  admission_no: { type: String },
  state: { type: String, enum: STATES },
  // NOTE: `branch` already existed on this entity pre-rebuild; it's added via
  // withCommonFields() below so it stays consistent (same enum, same index) with every other entity.
  form_status: {
    type: String,
    enum: ["Enquiry", "Applied", "Under Review", "Admitted", "Rejected"],
    default: "Enquiry",
  },
  class_sought: { type: String, enum: CLASS_SOUGHT, required: true },
  student_name: { type: String, required: true },
  gender: { type: String, enum: ["Male", "Female"], required: true },
  dob: { type: Date },
  height_cm: { type: Number },
  weight_kg: { type: Number },
  nationality: { type: String, default: "Indian" },
  religion: { type: String },
  mother_tongue: { type: String },
  caste: { type: String, enum: ["SC", "ST", "BC", "OC"] },
  id_mark_1: { type: String },
  id_mark_2: { type: String },
  blood_group: { type: String, enum: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"] },
  health_status: { type: String },
  passport_photo: { type: String },
  father_name: { type: String },
  father_qualification: { type: String },
  father_occupation: { type: String },
  father_mobile: { type: String, required: true },
  father_email: { type: String, lowercase: true, trim: true },
  mother_name: { type: String },
  mother_qualification: { type: String },
  mother_occupation: { type: String },
  mother_mobile: { type: String, required: true },
  mother_email: { type: String, lowercase: true, trim: true },
  family_income_pa: { type: Number },
  communication_address: { type: String, required: true },
  permanent_address: { type: String },
  same_as_communication: { type: Boolean, default: false },
  prev_school_1_standard: { type: String },
  prev_school_1_year: { type: String },
  prev_school_1_name: { type: String },
  prev_school_2_standard: { type: String },
  prev_school_2_year: { type: String },
  prev_school_2_name: { type: String },
  prev_school_3_standard: { type: String },
  prev_school_3_year: { type: String },
  prev_school_3_name: { type: String },
  doc_dob_cert: { type: Boolean, default: false },
  doc_passport_photos: { type: Boolean, default: false },
  doc_transfer_cert: { type: Boolean, default: false },
  doc_id_proof: { type: Boolean, default: false },
  doc_progress_record: { type: Boolean, default: false },
  doc_caste_cert: { type: Boolean, default: false },
  aadhaar_no: { type: String },
  submit_aadhaar: { type: Boolean, default: false },
  submit_ration_card: { type: Boolean, default: false },
  submit_passport: { type: Boolean, default: false },
  submit_other: { type: Boolean, default: false },
  source_direct: { type: Boolean, default: false },
  source_tele_call: { type: Boolean, default: false },
  source_outdoor_ads: { type: Boolean, default: false },
  staff_pro_name: { type: String },
  fee_payable_amount: { type: Number, required: true },
  term1_due_date: { type: Date },
  term2_due_date: { type: Date },
  term3_due_date: { type: Date },
  declaration_accepted: { type: Boolean, default: false },
  declaration_date: { type: String },
  student_signature: { type: String },
  parent_signature: { type: String },
  principal_signature: { type: String },
});

withCommonFields(admissionSchema);

export default mongoose.model("Admission", admissionSchema);
