import mongoose from "mongoose";
import { withCommonFields } from "./_baseSchema.js";

const expenditureSchema = new mongoose.Schema({
  exp_id: { type: String },
  category: {
    type: String,
    enum: [
      "Abacus/Vedic Maths Bills",
      "Admission Incentives",
      "Advertisements",
      "Bank Deposits",
      "Branch Visiting Allowance",
      "Building Repairs and Maintenance",
      "Building-I Rent",
      "Building-II Rent",
      "Bus Diesel",
      "Bus EMI-I",
      "Bus EMI-II",
      "Bus Fitness and Permit",
      "Bus Insurance",
      "Bus Repairs and Maintenance",
      "Bus Tax",
      "Chit Payments",
      "Class Room Furniture Bills",
      "Consultancy Bills",
      "DCEB Expenses",
      "Donations and Charities",
      "Drinking Water Bills",
      "Electricity Bills",
      "Electrical Equipments",
      "Electrical Repairs and Maintenance",
      "ERP AMC",
      "Functions and Celebrations",
      "Furniture Repairs and Maintenance",
      "Ground Rent",
      "Hire Vehicle Bills",
      "Housekeeping Bills",
      "ID/Badges Bills",
      "Interest on Loans",
      "Loans Repayments",
      "Look and Feel Bills",
      "Magazine Bills",
      "Management Fee",
      "Mobile and Internet Bills",
      "Municipal Water Bills",
      "Note Books Bills",
      "Office Furniture Bills",
      "Office Records Bills",
      "Other Miscellaneous Bills",
      "PF & ESI Payments",
      "Picnic and Tours Expenses",
      "Printing and Stationary Bills",
      "Profit Share",
      "Property Tax Bills",
      "Question Papers Bills",
      "Recognition Express",
      "Regular Uniform Bills",
      "Salaries and Wages",
      "School Activity Bills",
      "School Maintenance",
      "Sports Uniform Bills",
      "SSC Exam Fee Expenses",
      "Staff Welfare Bills",
      "Stationary Bills",
      "Student Diaries Bills",
      "Study and IIT Material Bills",
      "TDS Payments",
      "Text Books Bills",
      "Tie and Belts Bills",
      "Training Program Expenses",
      "Transport and Courier Expenses",
      "Travelling Allowance",
    ],
    required: true,
  },
  description: { type: String },
  amount: { type: Number, required: true },
  date: { type: Date, required: true },
  paid_to: { type: String },
  approved_by: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  branch: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Branch",
    required: true,
    index: true,
  },
});

withCommonFields(expenditureSchema);

export default mongoose.model("Expenditure", expenditureSchema);
